feat: zig language support (#1)
migrated from stkb#389

---------

* Fix tests trying to read differing cased files

Before this change:
```sh
$ node .config/do.mjs test
Error: ENOENT: no such file or directory, open './docs/specs/readme.md'
```

Tested on Linux (Manjaro, arch-based)

* Add support for Zig comments

Fix https://github.com/stkb/Rewrap/issues/388

* Update `parcel` to fix packaging errors with Node.js 18

See https://github.com/parcel-bundler/parcel/issues/8005

* build: package-lock.json

* ci: meaningless change to debug workflow

---------

Co-authored-by: Eric Eastwood <contact@ericeastwood.com>